[2025-06-30T10:28:41.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_fetch_dag.fetch_weather manual__2025-06-30T10:28:40.768899+00:00 [queued]>
[2025-06-30T10:28:41.292+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_fetch_dag.fetch_weather manual__2025-06-30T10:28:40.768899+00:00 [queued]>
[2025-06-30T10:28:41.293+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-30T10:28:41.300+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_weather> on 2025-06-30 10:28:40.768899+00:00
[2025-06-30T10:28:41.303+0000] {standard_task_runner.py:60} INFO - Started process 587 to run task
[2025-06-30T10:28:41.304+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_fetch_dag', 'fetch_weather', 'manual__2025-06-30T10:28:40.768899+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/weather_api_dag.py', '--cfg-path', '/tmp/tmp3vbloit0']
[2025-06-30T10:28:41.305+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask fetch_weather
[2025-06-30T10:28:41.340+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_fetch_dag.fetch_weather manual__2025-06-30T10:28:40.768899+00:00 [running]> on host 3b386aeca622
[2025-06-30T10:28:41.427+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_fetch_dag' AIRFLOW_CTX_TASK_ID='fetch_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T10:28:40.768899+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T10:28:40.768899+00:00'
[2025-06-30T10:28:41.537+0000] {logging_mixin.py:188} INFO - Failed to fetch data: {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}
[2025-06-30T10:28:41.538+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-30T10:28:41.552+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_fetch_dag, task_id=fetch_weather, execution_date=20250630T102840, start_date=20250630T102841, end_date=20250630T102841
[2025-06-30T10:28:41.597+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-30T10:28:41.633+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
