[2025-07-09T05:48:09.813+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Titanic_upload_file_to_s3_dag.upload_sql_to_s3 manual__2025-07-09T05:48:08.134002+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
